### ISSUE TITLE
Sublime Text won't build after upgrade

### ISSUE THREAD

**Issue by bullpencatcher** [b-g/processing-sublime#66]
Working with Sublime Text 3 on mac with the newest version of processing and ST. Since the upgrade that came to me yesterday for ST I cannot build processing from within ST. I get the error:

An output path must be specified.

I have another computer that I haven't upgraded ST on and it still works fine. Any advice on how to fix this or what I am doing wrong?

Bryan

**Comment by b-g** [comment]
Should be fixed now

**Comment by Sparragus** [comment]
I'm still having problems with building.

If the build system is set to 'Automatic', Sublime Text will try to use the default build system 'Processing 3'. The default build command for 'Processing 3' is:

` "cmd": ["processing-java", "--sketch=$file_path", "--run", "--force"],`
Reference: https://github.com/b-g/processing-sublime/blob/master/Build%20Systems/Processing%203.sublime-build#L3

In order to build a project, I need to manually select `Tools > Build System > Processing`.

My suggestion is to include the output option for all build commands, similar to how order build commands do.

Here's 36 seconds video showing the issue. 
https://www.youtube.com/watch?v=c-Z3BlFgk7Y

I've also sent a pull request fixing this. See https://github.com/b-g/processing-sublime/pull/71
